# Generated by Django 4.2.6 on 2024-06-14 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('num', models.IntegerField(default=1)),
                ('edited_by', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('submitted_date', models.DateTimeField(default=None, null=True, verbose_name='Submitted Date')),
            ],
        ),
        migrations.CreateModel(
            name='DrawLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_amount', models.FloatField(default=0.0)),
                ('description', models.CharField(max_length=250)),
                ('draw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.draw')),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('total', models.FloatField(default=0.0)),
                ('csi', models.CharField(max_length=6)),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/estimates/')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('total', models.FloatField(default=0.0)),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/exhibits/')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('total', models.FloatField(default=0.0)),
                ('csi', models.CharField(max_length=6)),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/estimates/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('O', 'On Hold')], max_length=1)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('w9', models.CharField(max_length=20)),
                ('csi', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('cname', models.CharField(default='', max_length=50)),
                ('cphone', models.CharField(default='', max_length=11)),
                ('cemail', models.EmailField(default='', max_length=254)),
                ('w9', models.CharField(max_length=20)),
                ('csi', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='SWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('description', models.CharField(default='', max_length=200)),
                ('total', models.FloatField()),
                ('pdf', models.FileField(upload_to='projectmanagement/SWOs')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.group')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('total', models.FloatField(default=0.0)),
                ('pdf', models.FileField(upload_to='projectmanagement/purchase_orders')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/plans/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
            ],
        ),
        migrations.CreateModel(
            name='MasterEstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.masterestimate')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.group')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
                ('subgroup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subgroup')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='masterestimate',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.AddField(
            model_name='masterestimate',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.AddField(
            model_name='masterestimate',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor'),
        ),
        migrations.CreateModel(
            name='LienRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Created Date')),
                ('type', models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], default='C', max_length=20)),
                ('pdf', models.FileField(default=None, null=True, upload_to='projectmanagement/lien_releases')),
                ('signed', models.BooleanField(default=False)),
                ('draw_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawlineitem')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.CreateModel(
            name='ExhibitLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=1)),
                ('unit_price', models.FloatField()),
                ('total', models.FloatField()),
                ('total_paid', models.FloatField(default=0.0)),
                ('exhibit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.exhibit')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.group')),
                ('subgroup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subgroup')),
            ],
        ),
        migrations.AddField(
            model_name='exhibit',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.estimate')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.group')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
                ('subgroup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subgroup')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='master_estimate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.masterestimate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor'),
        ),
        migrations.AddField(
            model_name='drawlineitem',
            name='exhibit_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.exhibitlineitem'),
        ),
        migrations.AddField(
            model_name='drawlineitem',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.AddField(
            model_name='draw',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
        ),
        migrations.CreateModel(
            name='DeductiveChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('total', models.FloatField(default=0.0)),
                ('pdf', models.FileField(upload_to='projectmanagement/deductive_change_orders')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('description', models.CharField(default='', max_length=200)),
                ('total', models.FloatField()),
                ('pdf', models.FileField(upload_to='projectmanagement/contracts')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('check_date', models.DateTimeField(verbose_name='Check Date')),
                ('check_num', models.CharField(max_length=12)),
                ('pdf', models.FileField(default=None, null=True, upload_to='projectmanagement/checks/')),
                ('draw_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawlineitem')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('total', models.FloatField(default=0.0)),
                ('pdf', models.FileField(upload_to='projectmanagement/change_orders')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
            ],
        ),
    ]
