# Generated by Django 4.2.6 on 2024-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitlineitem',
            name='total_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='exhibitlineitem',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
