# Generated by Django 4.1.6 on 2023-09-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
