# Generated by Django 4.1.6 on 2023-08-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_exhibitlineitem_estimatelineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitlineitem',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project'),
            preserve_default=False,
        ),
    ]
