# Generated by Django 4.2.6 on 2024-06-14 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_drawsummarylineitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='draw_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawsummarylineitem'),
        ),
        migrations.AlterField(
            model_name='lienrelease',
            name='draw_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawsummarylineitem'),
        ),
    ]
