# Generated by Django 4.1.6 on 2023-09-13 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_estimate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='vendor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
    ]
