# Generated by Django 4.2.6 on 2024-06-12 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_exhibitlineitem_total_paid_alter_exhibitlineitem_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('draw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.draw')),
                ('sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
            ],
        ),
        migrations.RemoveField(
            model_name='check',
            name='invoice_id',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddField(
            model_name='check',
            name='draw_item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawlineitem'),
            preserve_default=False,
        ),
    ]
