# Generated by Django 4.2.6 on 2024-06-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_drawlineitem_remove_check_invoice_id_delete_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawlineitem',
            name='draw_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='draw',
            name='submitted_date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Submitted Date'),
        ),
    ]
