# Generated by Django 4.2.6 on 2024-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0004_alter_check_draw_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawsummarylineitem',
            name='contract_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drawsummarylineitem',
            name='percent_complete',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='drawsummarylineitem',
            name='total_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
