# Generated by Django 4.2.6 on 2024-06-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_drawlineitem_draw_amount_alter_draw_submitted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='distributed',
        ),
        migrations.RemoveField(
            model_name='check',
            name='lien_release_pdf',
        ),
        migrations.RemoveField(
            model_name='check',
            name='lien_release_type',
        ),
        migrations.RemoveField(
            model_name='check',
            name='signed',
        ),
        migrations.CreateModel(
            name='LienRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Created Date')),
                ('type', models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], default='C', max_length=20)),
                ('pdf', models.FileField(default=None, null=True, upload_to='projectmanagement/lien_releases')),
                ('signed', models.BooleanField(default=False)),
                ('draw_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.drawlineitem')),
            ],
        ),
    ]
