# Generated by Django 4.1.6 on 2023-09-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_estimatelineitem_estimate_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='category',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='csi',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='project_id',
        ),
        migrations.CreateModel(
            name='MasterEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('total', models.FloatField(default=0.0)),
                ('csi', models.CharField(choices=[('1', 'General Requirement'), ('2', 'Site Works'), ('3', 'Concrete'), ('4', 'Masonry'), ('5', 'Metals'), ('6', 'Wood and Plastics'), ('7', 'Thermal and Moisture Protection'), ('8', 'Doors and Windows'), ('9', 'Finishes'), ('10', 'Specialties'), ('11', 'Equipment'), ('12', 'Furnishings'), ('13', 'Special Construction'), ('14', 'Conveying Systems'), ('15', 'Mechanical/Plumbing'), ('16', 'Electrical')], max_length=2)),
                ('category', models.CharField(choices=[('1', 'Civil Engineering'), ('2', 'Architecture'), ('3', 'Electrical Engineering'), ('4', 'Mechanical Engineering'), ('5', 'Plumbing'), ('6', 'Environmental'), ('7', 'Health Department'), ('8', 'Amenities'), ('9', 'Landscape')], max_length=50)),
                ('pdf', models.FileField(default=None, upload_to='projectmanagement/estimates/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor')),
            ],
        ),
        migrations.AddField(
            model_name='estimate',
            name='master_estimate',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.masterestimate'),
            preserve_default=False,
        ),
    ]
