# Generated by Django 5.1.4 on 2025-01-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0005_drawsummarylineitem_contract_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor'),
        ),
    ]
