# Generated by Django 4.2.6 on 2024-06-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_remove_check_distributed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='check_num',
            field=models.CharField(max_length=12),
        ),
    ]
