# Generated by Django 4.1.6 on 2023-09-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_remove_estimate_category_remove_estimate_csi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('unit_price', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('estimate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.masterestimate')),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.group')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.project')),
                ('sub_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subcontractor')),
                ('subgroup_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.subgroup')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectmanagement.vendor')),
            ],
        ),
    ]
