# Generated by Django 5.1.4 on 2025-01-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_purchaseorder_sub_id_alter_purchaseorder_vendor_id'),
        ('projectmanagement', '0007_auto_create_profiles'),
    ]

    operations = [
    ]
