# Generated by Django 4.2.6 on 2024-06-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0007_alter_check_check_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='check_total',
        ),
        migrations.AlterField(
            model_name='check',
            name='check_pdf',
            field=models.FileField(default=None, null=True, upload_to='projectmanagement/checks/'),
        ),
    ]
