# Generated by Django 4.2.6 on 2024-06-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0008_remove_check_check_total_alter_check_check_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='check_pdf',
            new_name='pdf',
        ),
    ]
