from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('all/', views.all, name='all'),
    path('new_proj/', views.new_proj, name='new_proj'),
    path('input_data/', views.input_data, name='input_data'),
    path('todo/', views.todo, name='todo'),
    path('all_subs/', views.all_subs, name='all_subs'),
    path('contract_view/<int:project_id>/<int:sub_id>', views.contract_view, name='contract_view'),
    path('edit_sub/<int:sub_id>/',views.edit_sub, name='edit_sub'),
    path('delete_sub/<int:sub_id>/', views.delete_sub, name='delete_sub'),
    path('new_draw/<int:project_id>', views.new_draw, name='new_draw'),
    path('new_invoice/<int:project_id>/<int:draw_id>/', views.new_invoice, name='new_invoice'),
    path('all_draws/<int:project_id>/', views.all_draws, name='all_draws'),
    path('all_plans/<int:project_id>', views.all_plans, name='all_plans'),
    path('delete_draw/<int:project_id>/', views.delete_draw, name='delete_draw'),
    path('edit_proj/<int:project_id>/', views.edit_proj, name='edit_proj'),
    path('add_signature/<int:invoice_id>/', views.add_signature, name='add_signature'),
    path('change_orders/<int:project_id>/<int:sub_id>/', views.change_orders, name='change_orders'),
    path('new_change_order/<int:project_id>/<int:sub_id>/', views.new_change_order, name='new_change_order'),
    path('delete_change_order/<int:co_id>/', views.delete_change_order, name='delete_change_order'),
    path('deductive_change_orders/<int:project_id>/<int:sub_id>/', views.deductive_change_orders, name='deductive_change_orders'),
    path('new_deductive_change_order/<int:project_id>/<int:sub_id>/', views.new_deductive_change_order, name='new_deductive_change_order'),
    path('purchase_orders/<int:project_id>/<int:sub_id>/', views.purchase_orders, name='purchase_orders'),
    path('new_purchase_order/<int:project_id>/<int:sub_id>/', views.new_purchase_order, name='new_purchase_order'),
    path('edit_invoice/<int:project_id>/<int:draw_id>/<int:invoice_id>/', views.edit_invoice, name='edit_invoice'),
    path('project_view/<int:project_id>/', views.project_view, name='project_view'),
    path('delete_proj/<int:project_id>/', views.delete_proj, name='delete_proj'),
    path('upload_plan/<int:project_id>/', views.upload_plan, name='upload_plan'),
    path('delete_plan/<int:project_id>', views.delete_plan, name='delete_plan'),
    path('invoice_view/<int:invoice_id>/', views.invoice_view, name='invoice_view'),
    path('sub_select/<int:project_id>/', views.sub_select, name='sub_select'),
    path('delete_invoice/<int:project_id>/<int:draw_id>/<int:invoice_id>/', views.delete_invoice, name='delete_invoice'),
    path('plan_view/<int:project_id>/<int:plan_id>/', views.plan_view, name='plan_view'),
    path('draw_view/<int:project_id>/<int:draw_id>/', views.draw_view, name='draw_view'),
    path('log_out/', views.log_out, name='logout'),
    path('accounts/', include('django.contrib.auth.urls')),
]
app_name = "reports"
