# Generated by Django 4.1.6 on 2023-06-04 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 6, 20, 457308), verbose_name='Start Date')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('O', 'On Hold')], max_length=1)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('pdf', models.FileField(default=None, upload_to='static/reports/SWOs')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('pdf', models.FileField(default=None, upload_to='static/reports/proposals/')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('pdf', models.FileField(default=None, upload_to='static/reports/plans/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 6, 20, 457308), verbose_name='Last Modified')),
                ('invoice_date', models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 6, 20, 457308), verbose_name='Invoice Date')),
                ('invoice_num', models.CharField(default='', max_length=20)),
                ('division_code', models.CharField(max_length=20)),
                ('method', models.CharField(choices=[('I', 'Invoice'), ('E', 'Exhibit'), ('P', 'Purchase Order')], default='I', max_length=1)),
                ('invoice_total', models.FloatField(default=0.0)),
                ('description', models.TextField()),
                ('lien_release_type', models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], default='N', max_length=20)),
                ('w9', models.CharField(max_length=20)),
                ('invoice_pdf', models.FileField(default=None, upload_to='static/reports/invoices/')),
                ('lien_release_pdf', models.FileField(default=None, upload_to='static/reports/lien_releases')),
                ('signed', models.BooleanField(default=None)),
                ('draw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.draw')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('pdf', models.FileField(default=None, upload_to='static/reports/exhibits/')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
        migrations.AddField(
            model_name='draw',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
        ),
        migrations.AddField(
            model_name='contractgroup',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
        ),
        migrations.AddField(
            model_name='contractgroup',
            name='sub_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('pdf', models.FileField(upload_to='static/reports/contracts')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
    ]
