# Generated by Django 4.1.6 on 2023-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='requested_by',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
            preserve_default=False,
        ),
    ]
