# Generated by Django 4.1.6 on 2023-05-17 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_requested_by_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('trade', models.CharField(max_length=100)),
                ('subcontractor', models.CharField(max_length=100)),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateTimeField(verbose_name='Invoice Date')),
                ('invoice_num', models.IntegerField(default=0)),
                ('subcontractor', models.CharField(max_length=50)),
                ('invoice_total', models.FloatField(verbose_name=0.0)),
                ('description', models.TextField()),
                ('lien_release_type', models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], max_length=20)),
                ('w9', models.CharField(max_length=20)),
                ('draw_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.draw')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_edit_date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contract')),
            ],
        ),
        migrations.CreateModel(
            name='SWO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contract')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
        ),
        migrations.AddField(
            model_name='draw',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
        ),
    ]
