# Generated by Django 4.1.6 on 2023-06-04 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zip',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 27, 28, 805426), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 27, 28, 805426), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 15, 27, 28, 805426), verbose_name='Invoice Date'),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
        migrations.CreateModel(
            name='DeductiveChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order_number', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='Order Date')),
                ('contractgroup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.contractgroup')),
            ],
        ),
    ]
