# Generated by Django 4.1.6 on 2023-05-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_contract_draw_exhibit_invoice_project_proposal_swo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('I', 'In Progress'), ('C', 'Completed'), ('O', 'On Hold')], max_length=1),
        ),
    ]
