# Generated by Django 4.1.6 on 2023-06-04 22:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_project_city_project_state_project_zip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorder',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='deductivechangeorder',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='exhibit',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='contractgroup_id',
        ),
        migrations.RemoveField(
            model_name='swo',
            name='contractgroup_id',
        ),
        migrations.AddField(
            model_name='changeorder',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/change_orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changeorder',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changeorder',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductivechangeorder',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/deductive_change_orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductivechangeorder',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deductivechangeorder',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibit',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibit',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/purchase_orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swo',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swo',
            name='sub_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 4, 4, 230625), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 4, 4, 231625), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 16, 4, 4, 231625), verbose_name='Invoice Date'),
        ),
        migrations.DeleteModel(
            name='ContractGroup',
        ),
    ]
