# Generated by Django 4.1.6 on 2023-06-05 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_changeorder_contractgroup_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeorder',
            name='name',
        ),
        migrations.RemoveField(
            model_name='deductivechangeorder',
            name='name',
        ),
        migrations.AddField(
            model_name='contract',
            name='total',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 20, 12, 28, 96501), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 20, 12, 28, 96501), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 4, 20, 12, 28, 96501), verbose_name='Invoice Date'),
        ),
    ]
