# Generated by Django 4.1.6 on 2023-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_title_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draw',
            name='name',
        ),
        migrations.AddField(
            model_name='draw',
            name='edited_by',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
