# Generated by Django 4.1.6 on 2023-06-06 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_changeorder_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='w9',
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='w9',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 46, 43, 88499), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 46, 43, 88499), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 18, 46, 43, 88499), verbose_name='Invoice Date'),
        ),
    ]
