# Generated by Django 4.1.6 on 2023-06-06 23:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_contract_name_remove_invoice_w9_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 25, 41, 905874), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 25, 41, 905874), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 17, 25, 41, 905874), verbose_name='Invoice Date'),
        ),
    ]
