# Generated by Django 4.1.6 on 2023-05-18 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_draw_name_draw_edited_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Last Modified')),
                ('edited_by', models.CharField(max_length=20)),
                ('pdf', models.FileField(upload_to='static/reports/plans/')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project')),
            ],
        ),
    ]
