# Generated by Django 4.1.6 on 2023-05-19 01:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcontractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addresss', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subcontractor',
        ),
        migrations.AddField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 31, 17, 694684), verbose_name='Start Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='division_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='method',
            field=models.CharField(choices=[('I', 'Invoice'), ('E', 'Exhibit'), ('P', 'Purchase Order')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 19, 31, 17, 694684), verbose_name='Invoice Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
        ),
    ]
