# Generated by Django 4.1.6 on 2023-06-09 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_exhibit_total_alter_draw_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swo',
            name='name',
        ),
        migrations.AddField(
            model_name='swo',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='swo',
            name='total',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 24, 36, 49669), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 24, 36, 49669), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 15, 24, 36, 49669), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='swo',
            name='pdf',
            field=models.FileField(upload_to='static/reports/SWOs'),
        ),
    ]
