# Generated by Django 4.1.6 on 2023-05-19 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_subcontractor_remove_invoice_subcontractor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='subcontractor',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='sub_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/invoices/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 9, 18, 13, 585912), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 9, 18, 13, 585912), verbose_name='Invoice Date'),
        ),
    ]
