# Generated by Django 4.1.6 on 2023-05-19 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_exhibit_subcontractor_exhibit_sub_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='last_edit_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sub_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='sub_name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 48, 21, 877720), verbose_name='Last Modified'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(default=None, upload_to='static/reports/invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lien_release_pdf',
            field=models.FileField(default=None, upload_to='static/reports/lien_releases'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sub',
            field=models.CharField(choices=[], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 48, 21, 877720), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 48, 21, 877720), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_num',
            field=models.CharField(default='', max_length=20),
        ),
    ]
