# Generated by Django 4.1.6 on 2023-06-09 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_swo_name_swo_description_swo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 1, 25, 107764), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 1, 25, 107764), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 1, 25, 107764), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
