# Generated by Django 4.1.6 on 2023-05-19 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_last_edit_date_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 58, 12, 641360), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 58, 12, 641360), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 12, 58, 12, 641360), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.subcontractor'),
        ),
    ]
