# Generated by Django 4.1.6 on 2023-06-09 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sub',
            new_name='sub_id',
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 22, 31, 349864), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 22, 31, 349864), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 16, 22, 31, 349864), verbose_name='Invoice Date'),
        ),
    ]
