# Generated by Django 4.1.6 on 2023-05-19 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcontractor',
            old_name='addresss',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 26, 41, 241745), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 26, 41, 241745), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 14, 26, 41, 241745), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='lien_release_type',
            field=models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], default='N', max_length=20),
        ),
    ]
