# Generated by Django 4.1.6 on 2023-05-19 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_rename_addresss_subcontractor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 33, 19, 67241), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 33, 19, 67241), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 17, 33, 19, 67241), verbose_name='Invoice Date'),
        ),
    ]
