# Generated by Django 4.1.6 on 2023-06-12 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_vendor_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 58, 52, 948824), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 58, 52, 948824), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 15, 58, 52, 948824), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cemail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='cphone',
            field=models.CharField(default='', max_length=11),
        ),
    ]
