# Generated by Django 4.1.6 on 2023-05-21 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='contract_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proposal',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='swo',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/SWOs'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 34, 13, 717082), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 34, 13, 717082), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 34, 13, 717082), verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='signed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='plan',
            name='pdf',
            field=models.FileField(default=None, upload_to='static/reports/plans/'),
        ),
    ]
