# Generated by Django 4.1.6 on 2023-06-12 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_alter_draw_start_date_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sub_id',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vendor_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reports.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 17, 11, 27, 658505), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 17, 11, 27, 658505), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 17, 11, 27, 658505), verbose_name='Invoice Date'),
        ),
    ]
