# Generated by Django 4.1.6 on 2023-08-14 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_remove_purchaseorder_sub_id_purchaseorder_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractor',
            name='category',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcontractor',
            name='csi',
            field=models.CharField(choices=[(1, 'General Requirement'), (2, 'Site Works'), (3, 'Concrete'), (4, 'Masonry'), (5, 'Metals'), (6, 'Wood and Plastics'), (7, 'Thermal and Moisture Protection'), (8, 'Doors and Windows'), (9, 'Finishes'), (10, 'Specialties'), (11, 'Equipment'), (12, 'Furnishings'), (13, 'Special Construction'), (14, 'Conveying Systems'), (15, 'Mechanical/Plumbing'), (16, 'Electrical')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 12, 17, 542112), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 12, 17, 542112), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 14, 12, 17, 542112), verbose_name='Invoice Date'),
        ),
    ]
