# Generated by Django 4.1.6 on 2023-08-15 00:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_remove_invoice_division_code_invoice_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='lien_release_pdf',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='lien_release_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='signed',
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 35, 7, 72687), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 35, 7, 72687), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 35, 7, 72687), verbose_name='Invoice Date'),
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 35, 7, 73625), verbose_name='Last Modified')),
                ('check_date', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 18, 35, 7, 73625), verbose_name='Check Date')),
                ('check_num', models.IntegerField()),
                ('check_total', models.FloatField(default=0.0)),
                ('distributed', models.CharField(max_length=50)),
                ('check_pdf', models.FileField(default=None, upload_to='static/reports/checks/')),
                ('lien_release_type', models.CharField(choices=[('F', 'Final'), ('C', 'Conditional'), ('N', 'N/A')], default='N', max_length=20)),
                ('lien_release_pdf', models.FileField(default=None, upload_to='static/reports/lien_releases')),
                ('signed', models.BooleanField()),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.invoice')),
            ],
        ),
    ]
