# Generated by Django 4.1.6 on 2023-08-16 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_group_invoice_vendor_id_alter_check_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('1', 'Civil Engineering'), ('2', 'Architecture'), ('3', 'Electrical Engineering'), ('4', 'Mechanical Engineering'), ('5', 'Plumbing'), ('6', 'Environmental'), ('7', 'Health Department'), ('8', 'Amenities'), ('9', 'Landscape')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='csi',
            field=models.CharField(choices=[('1', 'General Requirement'), ('2', 'Site Works'), ('3', 'Concrete'), ('4', 'Masonry'), ('5', 'Metals'), ('6', 'Wood and Plastics'), ('7', 'Thermal and Moisture Protection'), ('8', 'Doors and Windows'), ('9', 'Finishes'), ('10', 'Specialties'), ('11', 'Equipment'), ('12', 'Furnishings'), ('13', 'Special Construction'), ('14', 'Conveying Systems'), ('15', 'Mechanical/Plumbing'), ('16', 'Electrical')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='w9',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 25, 22, 769598), verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 25, 22, 769598), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 25, 22, 769598), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 25, 22, 769598), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 11, 25, 22, 769598), verbose_name='Invoice Date'),
        ),
    ]
