# Generated by Django 4.1.6 on 2023-08-17 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_invoice_group_id_invoice_subgroup_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draw',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='check',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 56, 51, 131415), verbose_name='Check Date'),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 56, 51, 131415), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='draw',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 56, 51, 131415), verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 56, 51, 131415), verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 20, 56, 51, 131415), verbose_name='Invoice Date'),
        ),
    ]
